### PR TITLE
Add a FAB for gitter

### PR DESCRIPTION
**Pull request by danrabbit**
Makes it a little more obvious you can get help in chat

screenshot from 2017-05-21 11 36 35

### CODE REVIEW

**Comment by btkostner** [comment]
Shouldn't this be fixed position in the bottom right. That way it is always visible?

**Comment by danrabbit** [comment]
Possibly, but I'm a bit concerned about it covering up other actions on mobile. Maybe @cassidyjames has a suggestion?

**Comment by btkostner** [comment]
We could add padding to the bottom of the page, so you can scoll up and have white space behind the button. You might still have a problem with covering things up if you only have 80 or so pixels of height, but I doubt that's a major problem.

**Comment by btkostner** [comment]
Going to merge. We can change it later if we need to.

**Pull request merged**
