### PR TITLE
slim down the log class

### PR DESCRIPTION
**Pull request by btkostner**
This kills winston library for a much smaller library called `Debug`. This PR does not implement it, I would like someone's approval before I start doing that. As such, tests will fail until it's fully implemented.

Debug normally doesn't have log types, but I figure it's something we use quite extensivly so I just extended Debug to add log levels, which is really the only reason this file exists. Everything should follow Debug convention. Running houston with `DEBUG=* npm run houston` will make it output _insane_ amounts of information about almost every package installed. `DEBUG=app:* npm run houston` would be the same as setting your configuration log level to `debug`.

For more information might as well see the [Debug library](https://github.com/visionmedia/debug/).

Advantages:
- Kills a library dependency
- Uses a library already heavily used (and installed), for example
  - Koa, our server library uses Debug
  - Ava, our testing library uses Debug
- Has browser support. Not really important right now, but useful when we start doing that

### CODE REVIEW

**Comment by lewisgoddard** [comment]
Checks are failing.

**Comment by btkostner** [comment]
> This PR does not implement it, I would like someone's approval before I start doing that. As such, tests will fail until it's fully implemented.

**Comment by lewisgoddard** [comment]
Whose permission are you seeking for this? Does this kill the ability to log to a file?

**Comment by btkostner** [comment]
It kills that function from the application side, but you can still pipe it into a file. It simplifies the application side a lot, and uses the same library most of our other libraries use for consistency.

Anyone's approval would be fine, I just don't want to create the huge PR that this will most likely become by adding a line to every file, if nobody agrees on it.

**Comment by lewisgoddard** [comment]
Browser support seems cool, and I guess you're maintaining it.

**Comment by btkostner** [comment]
Alright, I'll start moving the log files over then

**Pull request merged**
