### PR TITLE
Add a section to download the beta

### PR DESCRIPTION
**Pull request by danrabbit**
image

- [x] Could probably use better copy 
- [ ] Needs the links

### CODE REVIEW

**Comment by lewisgoddard** [comment]
At some point we should implement a matching copy of [regional and timestamp generation](https://github.com/elementary/website/blob/master/_backend/classify.current.php) so links have more up to date expires and actually use the geo-balancing.

Or make an API on the main site to fetch from houston (would guarantee it would match).

**Comment by harisvsulaiman** [comment]
Is that the juno download link in the commit?😀

**Comment by btkostner** [comment]
FYI, travis is complaining in master, so this is fine to merge when ready.

**Comment by danrabbit** [comment]
@harisvsulaiman Don't install that ISO if you downloaded it. It has an appdata break that can't be fixed by an update

**Comment by harisvsulaiman** [comment]
@danrabbit i downloaded and installed it. Updated with oibaf ppa and all hell broke loose.

Anyway eagerly waiting for public beta. 
If its a private beta i hope I'm on the list :smile:

**Pull request merged**
