### PR TITLE
New GitHub api

### PR DESCRIPTION
**Pull request by btkostner**
This replaces the old GitHub service file with a newer implimentation using [integrations](https://developer.github.com/early-access/integrations/).

### CODE REVIEW

**Comment by btkostner** [comment]
For sake of sanity someone should review this before I start adding the actual API functions back as it's about 500 lines so far.

As of right now what is working:
- JSON web tokens
- Authentication tokens
- Cache of authentication tokens
- Unit tests for the above

**Comment by emersion** [comment]
Fixes #226 (when this PR will be finished)

**Comment by btkostner** [comment]
At this point all of the API functions should be in. I added unit tests for each one to make sure all is good. Just need someone to double check before I start implementing.

Order of implementing:
- added needed fields to database
- update GitHub hooks
- update other files like dashboard
- add needed fields to message queue
- update flightcheck files to use new API

**Comment by btkostner** [comment]
At this point everything should be using the new GitHub API successfully.

There is currently one issue with uploading the finished packages to GitHub, but I opened an issue on the forum [here](https://platform.github.community/t/authentication-on-uploading-release-assets/713). We can still merge this as it shouldn't mess with any other operations.

**Pull request merged**
