### PR TITLE
add some markdown shields

### PR DESCRIPTION
**Pull request by btkostner**
Is it relevant to mvp? No

Houston needs to be hip and cool to all those young programmers, so this adds the [cool markdown shields](http://shields.io/) you see on GitHub project READMEs.

### CODE REVIEW

**Comment by fabianthoma** [comment]
:+1: But only if we unify on either Houston or AppHub here :stuck_out_tongue_winking_eye:

**Comment by btkostner** [comment]
I was going for more, Houston being the latest build status and AppHub being what version is available on elementary, but being that there is no difference right now, I'm not apposed.

**Comment by fabianthoma** [comment]
Also I'm not totally sure if and what kind of badges we'd want. @danrabbit might be the guy that should pitch in here.

**Comment by btkostner** [comment]
Putting this here for later:

`AppHub | Published` `AppHub | In Review` and `AppHub | Errors`

**Comment by btkostner** [comment]
I'm going to close this considering it's very dated and we have appcenter badges with a different project now.

**Pull request closed without merging**
