### PR TITLE
Issue #624: Add support for GitLab

### PR DESCRIPTION
**Pull request by rupertdev**
#624 

- added GitLab service
- added tests

### CODE REVIEW

**Comment by btkostner** [comment]
You should be able to run `npm start` and get the client interface.

**Comment by rupertdev** [comment]
Ready for review @btkostner

**Comment by btkostner** [comment]
Yep! Thanks for the PR! Just an FYI, it will probably be a while until I get to review this.

**Comment by rupertdev** [comment]
Hey @btkostner, any idea when you'll be able to get to this?

**Comment by btkostner** [comment]
@rupertdev I'm currently working on merging v2 worker into master so devs can build for Juno. After that, I'll take a look at this.

**Comment by btkostner** [comment]
My bad. I merged `v2-publishing` into `v2` which closed this PR. Reopening.

**Comment by rupertdev** [comment]
Any update on this @btkostner ?

**Comment by btkostner** [comment]
@rupertdev Sorry. I honestly forgot about this PR. Good news though. Master has been updated so the class gets resolved by the IoC container, so it can use the app configuration and what not. I'll work on fixing the conflicts and updating the class as needed when I get some down time this week.

**Comment by 4jNsY6fCVqZv** [comment]
@btkostner 
1. When will it be possible for me to get involved in app development for elementary OS via GitLab?
2. And do you think it's also a good idea to support Codeberg, which is based on Gitea and wants to be a free European alternative to GitHub? The registered association behind Codeberg is based in Berlin, Germany. https://blog.codeberg.org/codebergorg-launched.html

**Pull request closed without merging**
