### PR TITLE
add more information to changelog issue

### LINKED ISSUE #488: Uninformative invalid changes issue report
[The report in question](https://github.com/artemanufrij/metronome/issues/20)

This doesn't answer a couple of important questions:
* Is this my GitHub changelog, debian changelog, appstream changelog?
* What's the actual error output?
* Is there documentation that I can use to help correct the issue?

### PR DESCRIPTION
**Pull request by btkostner**
Fixes #488 

I tried to add all the needed information to the error. @danrabbit, Is there anything else that should be added?

### CODE REVIEW

**Comment by danrabbit** [comment]
The file path is `pipes/Debian/Changelog/warn.md` but the message says "GitHub" is that intentional?

**Comment by btkostner** [comment]
Yes it is. The error is because of the data we are putting in the Debian changelog file, which comes from the GitHub release body.

**Comment by danrabbit** [comment]
Cool cool. LGTM then. Much better 👍

**Comment by btkostner** [comment]
Approve the request then :P

**Pull request merged**
