### PR TITLE
Change debian parser to only use regex

### PR DESCRIPTION
**Pull request by btkostner**
Replaces https://github.com/elementary/houston/pull/551. Because parsing the Debian control file sucks.

### CODE REVIEW

**Comment by tom95** [comment]
Is there a way for me to confirm if this does indeed fix the issue?

**Comment by btkostner** [comment]
@tom95 sadly not without building this project and installing all the dependencies, which is a lot and probably not worth it. I did test this PR before submitting it, and it does fix your Debian control file issues for the `v0.1.2` release.

**Comment by btkostner** [comment]
It's worth noting that it did fail after that due to dependency issues:

```
   -- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
   -- Checking for modules 'zeitgeist-2.0;json-glib-1.0;rest-0.7;glib-2.0;gobject-2.0;gtk+-3.0;gio-2.0;gio-unix-2.0;wingpanel-2.0;libnotify'
   --   No package 'wingpanel-2.0' found
   CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:367 (message):
     A required package was not found
   Call Stack (most recent call first):
     /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:532 (_pkg_check_modules_internal)
     src/CMakeLists.txt:4 (pkg_check_modules)
```

**Comment by tom95** [comment]
Alright, I was hoping an additional tester may make it be released faster :P 

Thanks for the heads-up, I added the dependency, so I hope it'll be ready to go once this is merged!

**Comment by btkostner** [comment]
I'll let you know when this is deployed

**Comment by btkostner** [comment]
This should be deployed now. Sorry for the wait. Let me know if you keep on running into issues with the Debian control file test.

**Pull request merged**
